In [21]:
import pandas as pd
import glob

# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer Woo/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_04_30/*.csv")

# 2. Use list comprehension to read all files and concat them
df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1823 entries, 0 to 1822
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           1823 non-null   int64
 1   card_name              1822 non-null   object
 2   supertype              8 non-null      object
 3   subtype_a              117 non-null    object
 4   subtype_b              1769 non-null   object
 5   subtype_c              1231 non-null   object
 6   subtype_d              621 non-null    object
 7   subtype_e              47 non-null     object
 8   expansion_symbol       1822 non-null   object
 9   rarity                 1822 non-null   object
 10  artist_information     1819 non-null   object
 11  collectors_number      1822 non-null   object
 12  expansion_total_cards  1787 non-null   float64
 13  mana_cost              1773 non-null   object
 14  text_box               1766 non-null   object
 15  flavor_text            1308 non-null   object
 16  punch                  1058 non-null   object
 17  toughness              1057 non-null   object
 18  starting_loyalty       0 non-null      float64
 19  quantity               1817 non-null   object
dtypes: float64(2), int64(1), object(17)
memory usage: 285.0+ KB

In [23]:
df

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,1,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,Richard Kane Ferguson,69,383.0,U,Enchant Creature\nEnchanted creature gets +2+0...,Never underestimate the poweor of the soul unl...,NaN,NaN,NaN,1
1,2,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,Jeff A. Menges,73,383.0,XUU,Iceberg comes into play with X ice counters on...,NaN,NaN,NaN,NaN,1
2,3,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,Quinton Hoover,84,383.0,UU,B: Counter target spell that targets mistfolk.,"""Although my official log will state there is ...",1,2,NaN,1
3,4,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,"Ken Meyer, Jr.",100,383.0,1U,Enchant creature\nEnchanted creature has flyin...,"""Give me wings to fly and speed to strike. In ...",NaN,NaN,NaN,1
4,5,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,Tom Wänerstrand,310,383.0,2,"2, T: Target snow land is no longer snow.\n2, ...",NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,Cultivate,NaN,NaN,Sorcery,NaN,NaN,NaN,M11,Common,Anthony Palumbo,168,249.0,2G,Search your library for up to two basic land c...,"All seeds share a common bond, calling to each...",NaN,NaN,NaN,1
1819,1819,Giant Growth,NaN,NaN,Instant,NaN,NaN,NaN,M11,Common,Matt Cavotta,178,249.0,G,Target creature gets +3/+3 until end of turn.,NaN,NaN,NaN,NaN,1
1820,1820,Primal Cocoon,NaN,NaN,Enchantment,Aura,NaN,NaN,M11,Common,Daniel Ljunggren,191,249.0,G,Enchant creature\nAt the beginning of your upk...,NaN,NaN,NaN,NaN,2
1821,1821,Sacred Wolf,NaN,NaN,Creature,Wolf,NaN,NaN,M11,Common,Matt Stewart,196,249.0,2G,Sacred Wolf can't be the target of spells or a...,"""I raised my bow, and the wolf stared at me. U...",3.0,1.0,NaN,1
1822,1822,Wall of Vines,NaN,NaN,Creature,Plant,Wall,NaN,M11,Common,John Stanko,199,249.0,G,Defender (This creature can't attack.)\nReach ...,"Like all jungle plants, the vines must fight a...",0.0,3.0,NaN,1

In [24]:
df['permanent_id'] = range(1, len(df) +1)

In [25]:
df.tail()

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1818,1819,Cultivate,NaN,NaN,Sorcery,NaN,NaN,NaN,M11,Common,Anthony Palumbo,168,249.0,2G,Search your library for up to two basic land c...,"All seeds share a common bond, calling to each...",NaN,NaN,NaN,1
1819,1820,Giant Growth,NaN,NaN,Instant,NaN,NaN,NaN,M11,Common,Matt Cavotta,178,249.0,G,Target creature gets +3/+3 until end of turn.,NaN,NaN,NaN,NaN,1
1820,1821,Primal Cocoon,NaN,NaN,Enchantment,Aura,NaN,NaN,M11,Common,Daniel Ljunggren,191,249.0,G,Enchant creature\nAt the beginning of your upk...,NaN,NaN,NaN,NaN,2
1821,1822,Sacred Wolf,NaN,NaN,Creature,Wolf,NaN,NaN,M11,Common,Matt Stewart,196,249.0,2G,Sacred Wolf can't be the target of spells or a...,"""I raised my bow, and the wolf stared at me. U...",3.0,1.0,NaN,1
1822,1823,Wall of Vines,NaN,NaN,Creature,Plant,Wall,NaN,M11,Common,John Stanko,199,249.0,G,Defender (This creature can't attack.)\nReach ...,"Like all jungle plants, the vines must fight a...",0.0,3.0,NaN,1

In [ ]:
# 1. JUNCTION TABLE
# for each row, iterate through subtype columns
# if the subtype is nan, do nothing
# if the subtype is valid, add it to an array
# iterate through the array and query the parent table for the matching index
# insert the id and subtype into the junction table

In [26]:
row_subtypes = df.iloc[1059, 3:8].to_numpy()

In [27]:
row_subtypes

array([nan, 'Creature', 'Elf', 'Warrior', nan], dtype=object)

In [ ]:
import math
import numpy as np

for i, row in enumerate(df):
    permanent_id = df.iloc[i, 1]
    subtypes = df.iloc[i, 3:8].to_numpy()
        for type in subtypes:
            if math.isnan(type):
                continue
            else:
                cursor.execute("SELECT subtype_id FROM subtype WHERE subtype = %s", (type))
                subtype_id = cursor.fetchone()[0]
                cursor.execute("INSERT INTO permanent_junction_subtype (permnent_id, subtype_id) VALUES (%s, %s)" (permanent_id, subtype_id))
                connection.commit()

In [ ]:
# 2. PARENT TABLE
# create a list of all unique subtypes in the dataframe
# remove any instances of nan or blank subtypes
# find the longest subtype
# create table declaring subtype as VARCHAR() use the length of the longest subtype as the parameter for varchar

In [28]:
df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect',
       'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Sliver',
       'Eye', 'Gargoyle', 'Orgg', 'Avatar', 'Fungus', 'Kithkin',
       'Merfolk', 'Gorgon', 'Leech', 'Kor', 'Encahntment', 'Serpent',
       'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith', 'Cyclops',
       'Tribal', 'Forest', 'Ouphe', 'Myr', 'Treefolk', 'Instinct',
       'Island', 'Scarecrow', 'Hag', 'Noggle', 'Dwarf', 'Gobiln', 'Rhino',
       'Lizard', 'Artificer', 'Dragon', 'Unicorn', 'Vampire', 'Antelope',
       'Juggernaut', 'Vedalken', 'Ally', 'Funugs', 'Construct', 'Trap',
       'Kraken', 'Fish', 'Crocodile', 'Boar', 'Surrakar', 'Thopter'],
      dtype=object)

In [29]:
subtypes = df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

In [30]:
max(subtypes, key=len)

'Lichenthrope'

In [31]:
len(max(subtypes, key=len))

12

In [ ]:
longest = len(max(subtypes, key=len))

In [ ]:
cursor.execute(f"CREATE TABLE IF NOT EXISTS subtype (
                    subtype_id INT,
                    subtype VARCHAR({longest}) PRIMARY KEY
                )")

In [ ]:
for index, subtype in enumerate(subtypes, start=1):
    cursor.execute("INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)" (index, subtype))