In [1]:
import pandas as pd
import glob
import os
import numpy as np

In [2]:
path = r'C:\Users\Spencer Woo\Desktop\02_TCDB_Trading_Card_Database\Trading_Card_Collection_Download_2026_04_08'

In [3]:
all_files = glob.glob(os.path.join(path, "*.csv"))

In [4]:
df_list = [pd.read_csv(f) for f in all_files]

In [5]:
df = pd.concat(df_list, ignore_index=True)

In [25]:
df.tail(10)

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1050,NaN,Old Ghastbark,NaN,NaN,Creature,Treefolk,Warrior,NaN,Shadowmoor,Common,Thomas M. Baxa,232,301.0,3{G/W}{G/W},NaN,"""Beware of trees that talk. Their words are th...",3.0,6.0,NaN,9
1051,NaN,Presence of Gond,NaN,NaN,Enchantment,Aura,NaN,NaN,Shadowmoor,Common,Brandon Kitkouski,125,301.0,2G,"Enchant creature\nEnchanted creature has ""T: P...","""Here lies Gond, hero of Safehold Taldwen. May...",NaN,NaN,NaN,15
1052,NaN,Raven's Run Dragoon,NaN,NaN,Creature,Elf,Knight,NaN,Shadowmoor,Common,Daren Bader,235,301.0,2{G/W}{G/W},Raven's Run Dragoon can't be blocked by black ...,"""I have a gift. The ability to sense encroachi...",3.0,3.0,NaN,6
1053,NaN,Safehold Duo,NaN,NaN,Creature,Elf,Warrior,Shaman,Shadowmoor,Common,Izzy,238,301.0,3{G/W},"Whenever you play a green spell, Safehold Duo ...",NaN,2.0,4.0,NaN,13
1054,NaN,Safehold Elite,NaN,NaN,Creature,Elf,Scout,NaN,Shadowmoor,Common,Richard Whitters,239,301.0,1{G/W},Persist (When this creature is put into a grav...,"""I refuse to die—not at the hands of one such ...",2.0,2.0,NaN,5
1055,NaN,Safewright Quest,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Dan Scott,240,301.0,{G/W},Search your library for a Forest or Plains car...,Elves search for sources of beauty in a nighte...,NaN,NaN,NaN,6
1056,NaN,Shield of the Oversoul,NaN,NaN,Enchantment,Aura,NaN,NaN,Shadowmoor,Common,Steven Belledin,242,301.0,2{G/W},Enchant creature\nAs long as enchanted creatur...,NaN,NaN,NaN,NaN,6
1057,NaN,Toil to Renown,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Larry MacDougall,130,301.0,1G,"You gain 1 life for each tapped artifact, crea...","The last survivor of her patrol, the warrior r...",NaN,NaN,NaN,8
1058,NaN,Viridescent Wisps,NaN,NaN,Instant,NaN,NaN,NaN,Shadowmoor,Common,Jim Nelson,132,301.0,G,Target creature becomes green and gets +1/+0 u...,"In the wisps that night, the once timid boggar...",NaN,NaN,NaN,6
1059,NaN,Wildslayer Elves,NaN,NaN,Creature,Elf,Warrior,NaN,Shadowmoor,Common,Dave Kendall,133,301.0,3G,Wither (This deals damage to creatures in teh ...,Some elves battled too long in the deep shadow...,3.0,3.0,NaN,4

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060 entries, 0 to 1059
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           974 non-null    float64
 1   card_name              1059 non-null   object
 2   supertype              8 non-null      object
 3   subtype_a              40 non-null     object
 4   subtype_b              1037 non-null   object
 5   subtype_c              742 non-null    object
 6   subtype_d              390 non-null    object
 7   subtype_e              28 non-null     object
 8   expansion_symbol       1059 non-null   object
 9   rarity                 1059 non-null   object
 10  artist_information     1057 non-null   object
 11  collectors_number      1059 non-null   object
 12  expansion_total_cards  1024 non-null   float64
 13  mana_cost              1030 non-null   object
 14  text_box               1033 non-null   object
 15  flavor_text            695 non-null    object
 16  punch                  641 non-null    object
 17  toughness              641 non-null    object
 18  starting_loyalty       0 non-null      float64
 19  quantity               1056 non-null   object
dtypes: float64(3), object(17)
memory usage: 165.8+ KB

In [45]:
pd.unique(df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].values.ravel())

AttributeError: module 'pandas' has no attribute 'dropna'

In [46]:
all_subtypes = df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

In [47]:
all_subtypes

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect',
       'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Sliver',
       'Eye', 'Gargoyle', 'Orgg', 'Avatar', 'Fungus', 'Kithkin',
       'Merfolk', 'Gorgon', 'Leech', 'Kor', 'Encahntment', 'Serpent',
       'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith', 'Cyclops',
       'Tribal', 'Forest', 'Ouphe', 'Myr', 'Treefolk', 'Instinct'],
      dtype=object)

In [50]:
max(all_subtypes, key=len)

'Lichenthrope'

In [48]:
len(max(all_subtypes, key=len))

12

In [51]:
import mysql.connector
try:
    # 1. Establish the connection
    db_connection = mysql.connector.connect(
        host="localhost",
        user="admin",
        password="password",
        database="trading_card_database"
    )

    if db_connection.is_connected():
        print("Successfully connected to the database")

    # 2. Create a cursor to execute SQL queries
    cursor = db_connection.cursor()
    cursor.execute("SELECT DATABASE();")
    record = cursor.fetchone()
    print("You're connected to the database:", record)

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    # 3. Always close the connection
    if 'db_connection' in locals() and db_connection.is_connected():
        cursor.close()
        db_connection.close()
        print("MySQL connection is closed")

_IncompleteInputError: incomplete input (3285110914.py, line 23)

In [27]:
pd.unique(df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].values.ravel('K'))

array([nan, 'Artifact', 'Enchantment', 'Creature', 'Instant', 'Sorcery',
       'Land', 'Equipment', 'Encahntment', 'Tribal', 'Aura', 'Illusion',
       'Soldier', 'Lichenthrope', 'Elf', 'Wildebeests', 'Ceric',
       'Merchant', 'Elemental', 'Wizard', 'Ship', 'Pirate', 'Ox',
       'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric', 'Imp', 'Viashino',
       'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie', 'Rat', 'Rebel',
       'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton', 'Horror',
       'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat', 'Wurm',
       'Elephant', 'Golem', 'Mercenary', 'Spellshaper', 'Beast', 'Kavu',
       'Nomad', 'Hound', 'Insect', 'Druid', 'Incarnation', 'Nightmare',
       'Barbarian', 'Centaur', 'Troll', 'Human', 'Arcane', 'Turtle',
       'Spirit', 'Goblin', 'Dryad', 'Ogre', 'Giant', 'Frog', 'Faerie',
       'Snake', 'Plant', 'Sliver', 'Eye', 'Gargoyle', 'Orgg', 'Avatar',
       'Fungus', 'Kithkin', 'Merfolk', 'Gorgon', 'Leech', 'Kor',
       'Serpent', 'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith',
       'Ouphe', 'Myr', 'Treefolk', 'Instinct', 'Warrior', 'Mystic',
       'Crab', 'Shaman', 'Monk', 'Advisor', 'Assassin', 'Berserker',
       'Rogue', 'Mutant', 'Scout', 'Cyclops', 'Archer', 'Forest'],
      dtype=object)

In [8]:
df['expansion_symbol'].unique()

array(['Ice Age', 'Alliances', 'Visions', 'Portal', 'Stronghold',
       'Exodus', 'Portal 2', "Urza's Saga", "Urza's Legacy",
       'Starter 1999', 'Mercadian Masques', 'Sixth Edition', 'Nemesis',
       'Prophecy', 'Invasion', 'Seventh Edition', 'Planeshift', 'Odyssey',
       'Torment', 'Judgement', 'Legions', 'Scourge', 'Mirrodin',
       'Darksteel', 'Fifth Dawn', 'Fifth Dawn ', 'Champions of Kamigawa',
       'Betrayers of Kamigawa', 'Ninth Edition', 'Ravnica', 'Guildpact',
       'Eighth Edition', 'Dissension', 'Coldsnap', 'Time Spiral',
       'Time Spiral ', 'Time Sprial', 'Planar Chaos', 'Planar Chaos ',
       'Futuresight', 'Lorwyn', 'Morningtide', nan, 'Shadowmoor'],
      dtype=object)

In [9]:
## looks like there was a whole row of na this was just a data entry error.

In [10]:
df[df['expansion_symbol'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
911,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df['rarity'].unique()

array(['Common', 'Uncommon', 'Rare', 'Timeshifted Rare', nan],
      dtype=object)

In [12]:
df['artist_information'].unique()

array(['Richard Kane Ferguson', 'Jeff A. Menges', 'Quinton Hoover',
       'Ken Meyer, Jr.', 'Tom Wänerstrand', 'Scott Kirschner',
       'Cecil Fernando', 'Michael Danza', 'Bob Eggleton', 'Tom Kyffin',
       'Randy Gallegos', 'Adrian Smith', 'Christopher Rush', 'Brom',
       'Lubov', 'Doug Chaffee', 'Kaja Foglio', 'DiTerlizzi', 'Mark Tedin',
       "Di'Terlizzi", 'Heather Hudson', 'Douglas Shuler', 'Sam Wood',
       'Una Fricker', 'Melissa A. Benson', 'Jeffrey R. Busch',
       'Ron Spencer', 'Rebecca Guay', 'Keith Parkinson', 'Greg Simanson',
       'Berry', 'Greg Staples', 'Steve White', 'Daren Bader',
       'Pete Venters', 'Janine Johnston', 'John Matson', 'rk post',
       'Jeff Miracola', 'Dan Frazier', 'Phil Foglio', 'Carl Critchlow',
       'Michael Sutfin', 'Zina Saunders', 'Andrew Robinson',
       'Dameon Willich', 'Gerry Grace', 'Brian Snoddy', 'Mark Poole',
       'D. Alexander Gregory', 'Ian Miller', 'John Bolton', 'Gary Leach',
       'Clint Langley', 'Anson Maddocks', 'Richard Thomas',
       'David Seeley', 'Eric Peterson', 'Daniel Gelon',
       'Margaret Organ-Kean', 'Jesper Myrfors', 'Bradley Williams',
       'Terese Nielsen', 'Mike Ploog', 'Alan Pollack', 'Scott Hampton',
       'Greg & Tim Hildebrandt', 'Christopher Moeller', 'Ben Thompson',
       'Darrel Riche', 'Larry Elmore', 'Justin Sweet', 'Dave Dorman',
       'John Avon', 'Jeff Remmer', 'Kev Walker', 'Gary Ruddell',
       'Ciruelo', 'Mark Brill', 'Ron Spears', 'Alex Horley', 'Glen Angus',
       'Jeff Easley', 'Wayne England', 'Matt Cavota', 'Roger Raupp',
       'Adam Rex', 'Mark Romanoski', 'David Martin',
       'Edward P. Beard, Jr.', 'Trevor Hairsine', 'Rob Alexander',
       'David Day', 'Jeremy Jarvis', 'Richard Sardinha', 'Luca Zontini',
       'Tim Hildebrandt', 'Thomas M. Baxa', 'Tony Szczudlo',
       'Matthew D. Wilson', 'Justsin Sweet', 'Anthony S. Waters',
       'Jim Nelson', 'Chris Appelhans', 'Greg Hildebrandt',
       'Aleksi Briclot', 'Martina Pilcerova', 'Tsutomu Kawade',
       'Alex Horley-Orlandelli', 'Arnie Swekel', 'William Simpson',
       'Chippy', 'Dany Orizio', 'Michael Phillippi', 'Stephen Tappin',
       'Joel Thomas', 'Dave Allsop', 'Glenn Fabry', 'Jim Murray',
       'Paolo Parente', 'Cyril Van Der Haegen', 'Shishizaru',
       'Matt Thompson', 'Pat Lee', 'Zoltan Boros & Gabor Szikszai',
       'Ittoku', 'Nick Percival', 'Darrell Riche', 'Tom Hildebrandt',
       'Matt Cavotta', 'Brandon Kitkouski', 'James Wong', 'Jum Murray',
       'Tristan Elwell', 'Puddinhead', 'D. J. Cleland-Hura',
       'Ron Spears & Wayne Reynolds', 'Hideaki Takamura', 'Mark Zug',
       'Brian Hagan', 'Dan Scott', 'Brian Despain', 'Dan Dos Santos',
       'Henry G. Higgenbotham', 'Wayne Reynolds', 'Dennis Detwiler',
       'NéNé Thomas & Phillip Mosness', nan, 'Jeff Laubenstein',
       'Susan Van Camp', 'Parente', 'Liz Danforth', 'Ralph Horsley',
       'Drew Tucker', 'Stuart Griffin', 'Vance Kovacs', 'Randy Elliott',
       'Mike Dringenberg', 'Warren Mahy', 'Lars Grant-West',
       'Darren Bader', 'Scott M. Fischer', 'Steven Belledin',
       'E. M. Gist', 'Steve Ellis', 'Don Hazeltine', 'Steve Prescott',
       'Dave DeVries', 'Dave Kendall', 'Thomas Giorello',
       'Alex Horley Orlandelli', "William O'Connor", 'Tomas Giorello',
       'Volkan Baga', 'Jon Foster', 'Omar Rayyan', 'Lucio Parrillo',
       'Philip Straub', 'Khang Le', 'Heideaki Takamura', 'Eric Fortune',
       'Scott Altmann', 'Daarken', 'Nils Hamm', 'Jean-Sebastien Rossbach',
       'Tsutoma Kawade', 'James Kei', 'Franz Vohwinkel', 'John Donahue',
       'Matt Stewart', 'Michael Bruinsma', 'Brandon Dorman',
       'Chuck Lukacs', 'Jesper Ejsing', 'Larry MacDougall', 'Howard Lyon',
       'Omary Rayyan', 'Thomas Denmark', 'Dominick Domingo',
       'Terese Nielsen & Philip Tan', 'Jim Pavelec', 'Jasper Ejsing',
       'Franz Vohlwinkel', 'Carl Frank', 'Fred Fields', 'Shelly Wan',
       'Todd Lockwood', 'Quinton Hoover & Val Mayerik', 'Jim Pavelee',
       'Ron Brown', 'Izzy', 'Richard Whitters', 'Todd Luckwood'],
      dtype=object)

In [13]:
df['mana_cost'].unique()

array(['U', 'XUU', 'UU', '1U', '2', '3B', 'W', '4RR', '3GG', 'G', '2GG',
       '4R', '1R', '1WW', '3UU', '3U', '4U', '1UU', '2U', '1G', '1GG',
       '3G', '4WW', '3', '2W', '3R', '2G', '1W', '2R', '3W', 'WW', '2B',
       'B', '4W', '1B', 'BB', '1BB', 'R', '1RR', '4G', '7G', '6', '4',
       nan, 'BBB', '5GG', '2WW', '1', 'UB', 'RG', '1WU', '6G', '3WW',
       '6GG', '5G', '5R', '4GG', '5W', 'XW', '3BBG', '1RRW', '3{B/G}',
       '3BB', '1RW', '2{G/W}', '1g', 'GW', '3WB', 'WBB', '1UR', '4B',
       '2BB', '1WB', '1{W/B}', '2RG', '{R/G}', 'WU', '1GU', '{G/U}{G/U}',
       '2GU', 'GU', '2{G/U}', '0', '5', '4UU', '2UU', '2RR', '8R', '1RG',
       '3RR', '3GGGG', '3GGG', 'GG', '5WW', '5U', '5B', 'XG', '6U', '7U',
       '4BB', 'XU', '5BB', '6B', '6R', '6RR', '5RR', '1{U/B}', '4{U/B}',
       '2{U/B}', '3{U/B}', '{U/B}', '2{U/B}{U/B}', '4{B/R}', '1{B/R}',
       '{B/R}', '2{B/R}{B/R}', '2{R/G}', '4{R/G}{R/G}{R/G}', '1{R/G}',
       '4{R/G}{R/G}', '2{R/G}{R/G}', '4{R/G}', '{G/W}', '1{G/W}',
       '3{G/W}{G/W}', '2{G/W}{G/W}', '3{G/W}'], dtype=object)

In [14]:
df['supertype'].unique()

array([nan, 'Legend', 'Snow', 'Legendary'], dtype=object)

In [15]:
pip install pandas mysql-connector-python

Requirement already satisfied: pandas in c:\users\spencer woo\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: mysql-connector-python in c:\users\spencer woo\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\spencer woo\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\spencer woo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\spencer woo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\spencer woo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\spencer woo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_collection"
)

query = "SELECT * FROM permanent"
db = pd.read_sql(query, con=conn)

ProgrammingError: 1049 (42000): Unknown database 'trading_card_collection'

In [13]:
import pandas as pd
from sqlalchemy import create_engine

user = 'root'
password = 'password'
host = 'localhost'
port = '3306'
db_name = 'trading_card_collection'

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}")

In [15]:
pd.read_sql("SELECT * FROM permanent", con=engine)

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'trading_card_collection'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\spencer woo\anaconda3\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import mysql.connector

db_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_collection"
)

DatabaseError: 1130 (HY000): Host 'DESKTOP-KL9HVOD.fios-router.home' is not allowed to connect to this MySQL server