In [30]:
import pandas as pd

In [36]:
df = pd.read_csv(r"C:\Users\Spencer Woo\Desktop\collection.csv")

In [44]:
pd.set_option('display.max_rows', 150)

In [45]:
df

,permanent_id,card_name,type_line,expansion_symbol,rarity,artist_information,collectors_number,mana_cost,supertype,subtype,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,1,Essence Flare,Enchantment,Ice Age,Common,Richard Kane Ferguson,69/383,U,NaN,Aura,Enchant Creature\nEnchanted creature gets +2+0...,Never underestimate the poweor of the soul unl...,NaN,NaN,NaN,1
1,2,Iceberg,Enchantment,Ice Age,Uncommon,Jeff A. Menges,73/383,XUU,NaN,NaN,Iceberg comes into play with X ice counters on...,NaN,NaN,NaN,NaN,1
2,3,Mistfolk,Creature,Ice Age,Common,Quinton Hoover,84/383,UU,NaN,Illusion,B: Counter target spell that targets mistfolk.,"""Although my official log will state there is ...",1,2,NaN,1
3,4,Snow Devil,Enchantment,Ice Age,Common,"Ken Meyer, Jr.",100/383,1U,NaN,Aura,Enchant creature\nEnchanted creature has flyin...,"""Give me wings to fly and speed to strike. In ...",NaN,NaN,NaN,1
4,5,Arcum's Weathervane,Artifact,Ice Age,Uncommon,Tom Wänerstrand,310/383,2,NaN,NaN,"2, T: Target snow land is no longer snow.\n2, ...",NaN,NaN,NaN,NaN,1
5,6,Phantasmal Fiend,Creature,Alliances,Common,Scott Kirschner,57a/144,3B,NaN,Illusion,B: Phantasmal Fiend gets +1/-1 until end of tu...,NaN,1,5,NaN,1
6,7,Resistance Fighter,Creature,Visions,Common,Cecil Fernando,18,W,NaN,Soldier,Sacrifice Resistance Fighter: Target creature ...,"""My soldiers fought without hesitation, died w...",1,1,NaN,1
7,8,Fireblast,Instant,Visions,Common,Michael Danza,79,4RR,NaN,NaN,You may sacrifice two mountains instead of pay...,Embermages aren't well known for their diploma...,NaN,NaN,NaN,1
8,9,Lichenthrope,Creature,Visions,Common,Bob Eggleton,112,3GG,NaN,Lichenthrope,"For each 1 damage dealt to Lichenthrope, put a...",NaN,5,5,NaN,4
9,10,Quirion Ranger,Creature,Visions,Common,Tom Kyffin,117,G,Elf,NaN,Return a forest you control to owners's hand: ...,"""Respect the earth, for it will one day be you...",1,1,NaN,2
10,11,Stampeding Wildebeests,Creature,Visions,Common,Randy Gallegos,121,2GG,NaN,Wildebeests,"Trample\nDuring your upkeep, return a green cr...",Prayers for rain are answered with the thunder...,5,4,NaN,1
11,12,Lava Axe,Sorcery,Portal,Uncommon,Adrian Smith,137,4R,NaN,NaN,Lava Axe deals 5 damage to your opponent,"Swing your axe as a broom, to sweep away the foe",NaN,NaN,NaN,1
12,13,Volcanic Hammer,Sorcery,Portal,Uncommon,Christopher Rush,154,1R,NaN,NaN,Volcanic Hammer deals 3 damage to any one crea...,"Cast the weight as though it were a die, to se...",NaN,NaN,NaN,1
13,14,Contemplation,Enchantment,Stronghold,Common,Brom,4,1WW,NaN,NaN,"Whenever you successfully cast a spell, gain 1...","""How fascinating it is to watch the machinatio...",NaN,NaN,NaN,1
14,15,Soul Warden,Creature,Exodus,Uncommon,Randy Gallegos,21,W,NaN,Ceric,"Whenever any other creature comes into play, g...",Count carefully the souls and see that none ar...,1,1,NaN,4
15,16,Talas Merchant,Creature,Portal 2,Common,Lubov,50,1U,NaN,Merchant,NaN,The trader let loose a laugh that made all aro...,1,3,NaN,2
16,17,Air Elemental,Creature,Portal 2,Uncommon,Doug Chaffee,31,3UU,NaN,Elemental,Flying,"As insubstantial, and as powerful, as the wind...",4,4,NaN,2
17,18,Touch of Brilliance,Sorcery,Portal 2,Common,Kaja Foglio,58,3U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
18,19,Talas Researcher,Creature,Portal 2,Rare,Kaja Foglio,66,4U,NaN,Wizard,"On your turn, before you attack, you may tap T...","From time, knowledge.\nFrom knowledge, power.",1,1,NaN,1
19,20,False Summoning,Sorcery,Portal 2,Common,DiTerlizzi,40,1U,NaN,NaN,Play False Summoning only in response to anoth...,NaN,NaN,NaN,NaN,2
20,21,Talas Air Ship,Creature,Portal 2,Common,Mark Tedin,48,3U,NaN,Ship,Flying,"""Their ships pollute our air as they themselve...",3,2,NaN,2
21,22,Mystic Denial,Sorcery,Portal 2,Uncommon,Di'Terlizzi,41,1UU,NaN,NaN,Play Mystic Denial only in response to another...,NaN,NaN,NaN,NaN,2
22,23,Talas Scout,Creature,Portal 2,Common,Heather Hudson,52,1U,NaN,Pirate,Flying,"""Scouting a battle before you fight it is just...",1,2,NaN,2
23,24,Apprentice Sorcerer,Creature,Portal 2,Uncommon,Christopher Rush,32,2U,NaN,Wizard,"On your turn, before you attack, you may tap A...",NaN,1,1,NaN,2
24,25,Exhaustion,Sorcery,Portal 2,Rare,Kaja Foglio,37,2U,NaN,NaN,"At the beginning of your opponent's next turn,...",NaN,NaN,NaN,NaN,1
25,26,Talas Explorer,Creature,Portal 2,Common,Douglas Shuler,49,1U,NaN,Merchant,Flying,When Talas Explorer comes into play from your ...,1,1,NaN,2
26,27,Time Ebb,Sorcery,Portal 2,Common,Sam Wood,57,2U,NaN,NaN,Return any one creature from play to the top o...,"""The ogre had come from out of the blue, so th...",NaN,NaN,NaN,2
27,28,Talas Warrior,Creature,Portal 2,Rare,Douglas Shuler,53,1UU,NaN,Pirate,Talas Warrior can't be blocked,The sea is in their blood. Literally.,2,2,NaN,1
28,29,Monstrous Growth,Sorcery,Portal 2,Common,Una Fricker,133,1G,NaN,NaN,Any one creature gets +4/+4 until the end of t...,The nightstalker's little game of tease-the-sq...,NaN,NaN,NaN,2
29,30,Alluring Scent,Sorcery,Portal 2,Rare,Melissa A. Benson,121,1GG,NaN,NaN,"Choose any one creature. This turn, all creatu...",No earthly armor is protection against this sw...,NaN,NaN,NaN,1
30,31,Wild Ox,Creature,Portal 2,Uncommon,Jeffrey R. Busch,150,3G,NaN,Ox,Swampwalk (If defending player has any swamps ...,"It has the run of the swamps, and it knows it.",3,3,NaN,2
31,32,Sylvan Basalisk,Creature,Portal 2,Uncommon,Ron Spencer,146,3GG,NaN,Basilisk,"If Sylvan Basilisk attacks and is blocked, des...",NaN,2,4,NaN,1
32,33,River Bear,Creature,Portal 2,Uncommon,Una Fricker,144,3G,NaN,Bear,Islandwalk (If defending player has any island...,The bears had been isolated on an island for h...,3,3,NaN,2
33,34,Norwood Riders,Creature,Portal 2,Common,Rebecca Guay,139,3G,NaN,Elves,Norwood Riders can't be blocked by more than o...,"""Trade my moose? Sure—when I find a horse that...",3,3,NaN,2
34,35,Norwood Ranger,Creature,Portal 2,Common,Ron Spencer,138,G,Elf,NaN,NaN,Some trees bear deadly fruit.,1,2,NaN,2
35,36,Norwood Archers,Creature,Portal 2,Common,Rebecca Guay,136,3G,NaN,Elves,Norwood Archers can block creatures with flying.,"""'Air superiority?' Not while our archers scan...",3,3,NaN,2
36,37,Golden Bear,Creature,Portal 2,Common,Una Fricker,127,3G,NaN,Bear,NaN,The elvish scout was scrupulous about the trut...,4,3,NaN,2
37,38,Bear Cub,Creature,Portal 2,Common,Ron Spencer,123,1G,NaN,Bear,NaN,Every little cub has its mother's teeth to gua...,2,2,NaN,3
38,39,Ironhoof Ox,Creature,Portal 2,Common,Una Fricker,130,3GG,NaN,Ox,Ironhoof Ox can't be blocked by more than one ...,The good news is it's vegetarian. The bad news...,4,4,NaN,2
39,40,Angel of Fury,Creature,Portal 2,Rare,Keith Parkinson,7,4WW,NaN,Angel,Flying\nIf Angel of Fury is put into your grav...,NaN,3,5,NaN,1
40,41,Righteous Charge,Sorcery,Portal 2,Uncommon,Jeffrey R. Busch,20,1WW,NaN,NaN,All your creatures get +2/+2 until the end of ...,NaN,NaN,NaN,NaN,1
41,42,Dragon Blood,Artifact,Urza's Saga,Uncommon,Greg Simanson,293/350,3,NaN,NaN,"3, T: Put a +1/+1 counter on target creature.","Fire in the blood, fire in the belly.",NaN,NaN,NaN,1
42,43,Songstitcher,Creature,Urza's Saga,Uncommon,Berry,52/350,W,NaN,Cleric,1W: Target attacking creature with flying deal...,The true names of birds are songs woven into t...,1,1,NaN,1
43,44,Waylay,Instant,Urza's Saga,Uncommon,Greg Staples,56/350,2W,NaN,NaN,Put three Knight tokens into play.\nTreat thes...,"""You reek of corruption,"" spat the knight. ""Wh...",NaN,NaN,NaN,1
44,45,Crazed Skirge,Creature,Urza's Saga,Uncommon,Ron Spencer,125/350,3B,NaN,Imp,Flying\nCrazed Skirge is unaffected by summoni...,They are Phyrexia's couriers; the messages the...,2,2,NaN,1
45,46,Viashino Runner,Creature,Urza's Saga,Common,Steve White,224/350,3R,NaN,Viashino,Viashino Runner cannot be blocked by only one ...,"""It moved this way, an' that way, an' then bef...",3,2,NaN,4
46,47,Treetop Rangers,Creature,Urza's Saga,Common,Daren Bader,279/350,2G,NaN,Elves,Treetop Rangers cannot be blocked except by cr...,"""If you can't catch them, cut the trees down f...",2,2,NaN,4
47,48,Sluggishness,Enchantment,Urza's Legacy,Common,Pete Venters,92/143,1R,NaN,NaN,Enchanted creature cannot block.\nWhen Sluggis...,Vark decided to lie down and think of a good e...,NaN,NaN,NaN,3
48,49,Lone Wolf,Creature,Starter 1999,Common,Una Fricker,130/173,2G,NaN,Wolf,You may have Lone Wolf deal its combat damage ...,NaN,2,2,NaN,1
49,50,Norwood Archers,Creature,Starter 1999,Common,Rebecca Guay,137/173,3G,Elf,NaN,Norwood Archers can block as though it had fly...,"""'Air superiority?' Not while our archers scan...",3,3,NaN,1
50,51,Sacred Nectar,Sorcery,Starter 1999,Common,Janine Johnston,26/173,1W,NaN,NaN,You gain 4 life.,"""For he on honey-dew hath fed, And drunk the m...",NaN,NaN,NaN,1
51,52,Stone Rain,Sorcery,Starter 1999,Common,John Matson,118/173,2R,NaN,NaN,Destroy target land.,NaN,NaN,NaN,NaN,1
52,53,Breath of Life,Sorcery,Starter 1999,Uncommon,Di'Terlizzi,10/173,3W,NaN,NaN,Put target creature card from your graveyard i...,NaN,NaN,NaN,NaN,1
53,54,Veteran Cavalier,Creature,Starter 1999,Uncommon,rk post,30/173,WW,NaN,Knight,Attacking doesn't cause Veteran cavalier to tap.,Spirit is the sword and experience the sharpen...,2,2,NaN,1
54,55,Wild Griffin,Creature,Starter 1999,Common,Jeff Miracola,31/173,2W,NaN,Griffin,Flying,"Two little goblins, out in the sun. Down came ...",2,2,NaN,1
55,56,Extinguish,Instant,Starter 1999,Common,Douglas Shuler,37/173,1U,NaN,NaN,Counter target sorcery spell.,NaN,NaN,NaN,NaN,1
56,57,Ingenious Thief,Creature,Starter 1999,Common,Dan Frazier,40/173,1U,NaN,Thief,"Flying\nWhen Ingenious Thief comes into play, ...",NaN,1,1,NaN,1
57,58,Sleight of Hand,Sorcery,Starter 1999,Common,Phil Foglio,51/173,U,NaN,NaN,Look at the top two cards of your library. Put...,NaN,NaN,NaN,NaN,1
58,59,Bog Raiders,Creature,Starter 1999,Common,Carl Critchlow,66/173,2B,NaN,Zombie,Swampwalk (This creature is unblockable as lon...,Those who live amid decay must expect scavengers,2,2,NaN,1
59,60,Muck Rats,Creature,Starter 1999,Common,Una Fricker,84/173,B,NaN,Rat,NaN,"""Just as some fool said it couldn't get worse,...",1,1,NaN,1
60,61,Jhovall Queen,Creature,Mercadian Masques,Rare,Michael Sutfin,25/350,4WW,NaN,Rebel,Attacking doesn't cause Jhovall Queen to tap.,War-trained jhovalls eat twice their weight in...,4,7,NaN,4
61,62,Ardent Militia,Creature,Sixth Edition,Uncommon,Zina Saunders,3/350,4W,NaN,Soldier,Attacking doesn't cause Ardent Militia to tap.,"Some fight for honor and some for gold, but th...",2,5,NaN,1
62,63,Armored Pegasus,Creature,Sixth Edition,Common,Andrew Robinson,5/350,1W,NaN,Pegasus,Flying,"Asked how it survived a run-in with a bog imp,...",1,2,NaN,1
63,64,Castle,Enchantment,Sixth Edition,Uncommon,Dameon Willich,6/50,3W,NaN,NaN,Untapped creatures you control get +0/2.,"""Hang out our banners on the outward walls;/Th...",NaN,NaN,NaN,1
64,65,Circle of Protection: White,Enchantment,Sixth Edition,Common,Gerry Grace,12/350,1W,NaN,NaN,1: The next time a white source of your choice...,NaN,NaN,NaN,NaN,1
65,66,D'Avenant Archer,Creature,Sixth Edition,Common,Douglas Shuler,15/350,2W,NaN,Soldier,T: D'Avenant Archer deals 1 damage to target a...,"Avenant's archers are also trained as poets, s...",1,2,NaN,1
66,67,Disenchant,Instant,Sixth Edition,Common,Brian Snoddy,16/350,1W,NaN,NaN,Destroy target artifact or enchantment,NaN,NaN,NaN,NaN,3
67,68,Healing Salve,Instant,Sixth Edition,Common,Dan Frazier,22/350,W,NaN,NaN,Choose one—Target player gains 3 life; or prev...,NaN,NaN,NaN,NaN,2
68,69,Hero's Resolve,Enchantment,Sixth Edition,Common,Pete Venters,24/350,1W,NaN,NaN,Enchanted creature gets +1/+5.,"""Destiny, chance, fate, fortune—they're all ju...",NaN,NaN,NaN,1
69,70,Mesa Falcon,Creature,Sixth Edition,Common,Mark Poole,31/350,1W,NaN,Bird,Flying\n1W: Mesa Falcon gets +0/+1 until end o...,"""The faith of Serra is borne on wings of hope....",1,1,NaN,1
70,71,Samite Healer,Creature,Sixth Edition,Common,Tom Wänerstrand,40/350,1W,NaN,Cleric,T: Prevent the next 1 damage to target creatur...,Healers ultimatelly acquire the divine gifts o...,1,1,NaN,1
71,72,Venerable Monk,Creature,Sixth Edition,Common,D. Alexander Gregory,50/350,2W,NaN,Cleric,"When Venerable Monk comes into play, you gain...",His presence brings not only a strong arm but ...,2,2,NaN,1
72,73,Warrior's Honor,Instant,Sixth Edition,Common,D. Alexander Gregory,53/350,2W,NaN,NaN,Creatures you control get +1/+1 until end of t...,NaN,NaN,NaN,NaN,1
73,74,Prodiga Sorcerer,Creature,Sixth Edition,Common,Douglas Shuler,88/350,2U,NaN,Wizard,T: Prodigal sorcerer deals 1 damage to target ...,Occasionally members of the Institute of Arcan...,1,1,NaN,1
74,75,Tidal Surge,Sorcery,Sixth Edition,Common,Doug Chaffee,102/350,1U,NaN,NaN,Tap up to three target creatures without flying.,"""It is nature that gives us our boundaries and...",NaN,NaN,NaN,1
75,76,Wind Drake,Creature,Sixth Edition,Common,Zina Saunders,106/350,2U,NaN,Drake,Flying,"""No bird soars too high, if he soars with his ...",2,2,NaN,1
76,77,Blood Pet,Creature,Sixth Edition,Common,Brom,115/350,B,NaN,Thrull,Sacrifice Blood Pet: Add B to your mana pool.,"""You are wrong,"" Volrath said. ""I do not hate ...",1,1,NaN,1
77,78,Drudge Skeletons,Creature,Sixth Edition,Common,Ian Miller,123/350,1B,NaN,Skeleton,B: Regenerate Drudge Skeletons.,"""The dead make good soldiers. They can't disob...",1,1,NaN,1
78,79,Enfeeblement,Enchantment,Sixth Edition,Common,John Bolton,125/350,BB,NaN,NaN,Enchanted creature gets -2/-2.,"""If it is weak, either kill it or ignore it. A...",NaN,NaN,NaN,1
79,80,Gravebane Zombie,Creature,Sixth Edition,Uncommon,Gary Leach,133/350,3B,NaN,Zombie,When Gravebane Zombie would be put into a grav...,NaN,3,2,NaN,1
80,81,Hidden Horror,Creature,Sixth Edition,Uncommon,Clint Langley,137/350,1BB,NaN,Horror,"When Hidden Horror comes into play, choose and...",NaN,4,4,NaN,1
81,82,Mischievous Poltergeist,Creature,Sixth Edition,Uncommon,Di'Terlizzi,144/350,2B,NaN,Ghost,Flying\nPay 1 life: Regenerate Mischievous Pol...,"""The past is a ghost that haunts you from the ...",1,1,NaN,1
82,83,Anaba Bodyguard,Creature,Sixth Edition,Common,Anson Maddocks,164/350,3R,NaN,Minotaur,"First strike\n""Not all minotaurs are tribal. S...",NaN,2,3,NaN,1
83,84,Fit of Rage,Sorcery,Sixth Edition,Common,Douglas Shuler,178/350,1R,NaN,NaN,Target creature gets +3/+3 and gains first str...,"""Anger is fleeting; remorse is eternal.""\n—Kar...",NaN,NaN,NaN,1
84,85,Lightning Blast,Instant,Sixth Edition,Common,Richard Thomas,193/350,3R,NaN,NaN,Lightning Blast deals 4 damage to target creat...,"""Those who fear the darkness have never seen w...",NaN,NaN,NaN,1
85,86,Pyrotechnics,Sorcery,Sixth Edition,Common,Anson Maddocks,199/350,4R,NaN,NaN,Pyrotechnics deals 4 damage divided any way yo...,"""Hi!ni!ya! Behold the man of flint, that's me!...",NaN,NaN,NaN,1
86,87,Sabretooth Tiger,Creature,Sixth Edition,Common,Melissa A. Benson,203/350,2R,NaN,Tiger,"First strike\n""Not all minotaurs are tribal. S...","""I fear anything with teeth measured in handsp...",2,1,NaN,1
87,88,Shock,Instant,Sixth Edition,Common,Randy Gallegos,206/350,R,NaN,NaN,Shock deals 2 damage to target creature or pla...,Lightning tethers souls to the world.\n—Kor sa...,NaN,NaN,NaN,1
88,89,Tremor,Sorcery,Sixth Edition,Common,Pete Venters,211/350,R,NaN,NaN,Tremor deals 1 damage to each creature without...,"""Where do you run when the earth becomes your ...",NaN,NaN,NaN,1
89,90,Wall of Fire,Creature,Sixth Edition,Uncommon,Richard Thomas,216/350,1RR,NaN,Wall,(Walls can't attack.)\nR: Wall of Fire gets +1...,"""Struggle, and you will only fan the flames.""\...",0,5,NaN,1
90,91,Creeping Mold,Sorcery,Sixth Edition,Uncommon,David Seeley,220/350,2GG,NaN,NaN,"Destroy target artifact, land, or enchantment.","""Mold could catch you.""\n—Suq'Ata insult",NaN,NaN,NaN,1
91,92,Giant Growth,Instant,Sixth Edition,Common,Di'Terlizzi,233/350,G,NaN,NaN,Target creature gets +3/+3 until end of turn.,NaN,NaN,NaN,NaN,1
92,93,Giant Spider,Creature,Sixth Edition,Common,Randy Gallegos,234/350,3G,NaN,Spider,Giant Spider can block as though it had flying.,"It's not far into the trap, as the crow flies.",2,4,NaN,1
93,94,Llanowar Elves,Creature,Sixth Edition,Common,Anson Maddocks,239/350,G,Elf,NaN,T: Add G to your mana pool.,One bone broken for every twig snapped underfo...,1,1,NaN,1
94,95,Panther Warriors,Creature,Sixth Edition,Common,Eric Peterson,243/350,4G,Cat,Warrior,NaN,The dogs of war are nothing compared to the cats.,6,3,NaN,2
95,96,Rampant Growth,Sorcery,Sixth Edition,Common,Tom Kyffin,246/350,1G,NaN,NaN,Search your library for a basic land card and ...,Rath forces plants from its surface as one pre...,NaN,NaN,NaN,1
96,97,Scaled Wurm,Creature,Sixth Edition,Common,Daniel Gelon,251/350,7G,NaN,Wurm,NaN,"""Flourishing during the Ice Age, these wurms w...",7,6,NaN,1
97,98,Trained Armodon,Creature,Sixth Edition,Common,Gary Leach,257/350,1GG,NaN,Elephant,NaN,These are its last days. Better to grow broad ...,3,3,NaN,1
98,99,Mana Prism,Artifact,Sixth Edition,Uncommon,Margaret Organ-Kean,297/350,3,NaN,NaN,T: Add one colorless mana to your mana pool.\n...,NaN,NaN,NaN,NaN,1
99,100,Obsianus Golem,Artifact Creature,Sixth Edition,Uncommon,Jesper Myrfors,303/350,6,NaN,Golem,NaN,"""The foot stone is connected to the ankle ston...",4,6,NaN,1
100,101,Rod of Ruin,Artifact,Sixth Edition,Uncommon,Christopher Rush,309/350,4,NaN,NaN,"3, T: Rod of Ruin deals 1 damage to target cre...",NaN,NaN,NaN,NaN,1
101,102,Fresh Volunteers,Creature,Mercadian Masques,Common,Jeff Miracola,20/350,1W,NaN,Rebel,NaN,Every Cho-Arrim villager is a potential warrio...,2,2,NaN,1
102,103,Chameleon Spirit,Creature,Mercadian Masques,Uncommon,Bradley Williams,65/350,3U,NaN,Illusion,"As Chameleon Spirit comes into play, choose a ...",NaN,X,X,NaN,1
103,104,Diplomatic Immunity,Enchantment,Mercadian Masques,Common,Terese Nielsen,75/350,1U,NaN,NaN,Enchanted creature can't be the target of spel...,NaN,NaN,NaN,NaN,1
104,105,Bog Smugglers,Creature,Mercadian Masques,Common,Mike Ploog,117/350,1BB,NaN,Mercenary,Swampwalk (This creature is unblockable as lon...,They slide over the bog like oil across glass.,2,2,NaN,1
105,106,Deepwood Ghoul,Creature,Mercadian Masques,Common,Alan Pollack,131/350,2B,NaN,Zombie,Pay 2 life: Regenerate Deepwood Ghoul.,They feed on the living to stay undead.,2,1,NaN,1
106,107,Flaming Sword,Enchantment,Mercadian Masques,Common,Randy Gallegos,190/350,1R,NaN,NaN,You may play Flaming Sword any time you could ...,"""It's not Talruum crystal, but I must admit—it...",NaN,NaN,NaN,1
107,108,Uphill Battle,Enchantment,Mercadian Masques,Uncommon,Pete Venters,222/350,2R,NaN,NaN,Creatures your opponents play come into play t...,Cho-Manno knew he had no choice but to ally wi...,NaN,NaN,NaN,1
108,109,Rushwood Herbalist,Creature,Mercadian Masques,Common,Terese Nielsen,265/350,2G,NaN,Spellshaper,"G, T, Discard a card from you hand: Regenerate...","When generals gather their armies, healers gat...",2,2,NaN,1
109,110,Fountain of Cho,Land,Mercadian Masques,Uncommon,Scott Hampton,317/350,NaN,NaN,NaN,Fountain of Cho comes into play tapped.\nT: Pu...,NaN,NaN,NaN,NaN,4
110,111,"Lin Sivvi, Defiant Hero",Creature,Nemesis,Rare,rk post,12/143,1WW,Rebel,Legend,"X, T: Search your library for a Rebel card wit...",NaN,1,3,NaN,4
111,112,Mana Cache,Enchantment,Nemesis,Rare,rk post,92/142,1RR,NaN,NaN,"At the end of each player's turn, put a charge...",NaN,NaN,NaN,NaN,1
112,113,Murderous Betrayal,Enchantment,Nemesis,Rare,Randy Gallegos,61/143,BBB,NaN,NaN,"BB, Pay half your life rounded up: Destroy tar...","In darkness, the assassin sneaked into the vil...",NaN,NaN,NaN,1
113,114,Skyshroud Behemoth,Creature,Nemesis,Rare,Eric Peterson,116/143,5GG,NaN,Beast,Fading 2 (This creature comes into play with t...,NaN,10,10,NaN,1
114,115,Defiant Falcon,Creature,Nemesis,Common,Heather Hudson,6/143,1W,Rebel,Bird,"Flying\n4, T: Search your library for a Rebel ...",NaN,1,1,NaN,4

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Spencer Woo\Downloads\Trading_Card_Collection - Sheet1(1).csv")

In [4]:
selected_cols = ['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d']
unique_values = df[selected_cols].stack().unique()
unique_list = unique_values.tolist()
print(unique_list)

['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact', 'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests', 'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship', 'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric', 'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie', 'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton', 'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat', 'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper', 'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect', 'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian', 'Centaur', 'Spirit', 'Equipment']

In [5]:
len(unique_list)

65

In [6]:
subtypes = {
    'subtype': ['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact', 'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests', 'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship', 'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric', 'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie', 'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton', 'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat', 'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper', 'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect', 'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian', 'Centaur', 'Spirit', 'Equipment']
}

In [7]:
subtypes

{'subtype': ['Enchantment',
  'Aura',
  'Creature',
  'Illusion',
  'Artifact',
  'Soldier',
  'Instant',
  'Lichenthrope',
  'Elf',
  'Wildebeests',
  'Sorcery',
  'Ceric',
  'Merchant',
  'Elemental',
  'Wizard',
  'Ship',
  'Pirate',
  'Ox',
  'Basilisk',
  'Bear',
  'Elves',
  'Angel',
  'Cleric',
  'Imp',
  'Viashino',
  'Wolf',
  'Knight',
  'Griffin',
  'Thief',
  'Zombie',
  'Rat',
  'Rebel',
  'Pegasus',
  'Bird',
  'Drake',
  'Thrull',
  'Skeleton',
  'Horror',
  'Ghost',
  'Minotaur',
  'Tiger',
  'Wall',
  'Spider',
  'Cat',
  'Warrior',
  'Wurm',
  'Elephant',
  'Golem',
  'Mercenary',
  'Spellshaper',
  'Land',
  'Beast',
  'Kavu',
  'Nomad',
  'Mystic',
  'Hound',
  'Insect',
  'Druid',
  'Incarnation',
  'Nightmare',
  'Crab',
  'Barbarian',
  'Centaur',
  'Spirit',
  'Equipment']}

In [8]:
su = pd.DataFrame(subtypes)

In [9]:
su

        subtype
0   Enchantment
1          Aura
2      Creature
3      Illusion
4      Artifact
..          ...
60         Crab
61    Barbarian
62      Centaur
63       Spirit
64    Equipment

[65 rows x 1 columns]

In [10]:
su['subtype_id'] = range(1, len(su) + 1)

In [11]:
su

        subtype  subtype_id
0   Enchantment           1
1          Aura           2
2      Creature           3
3      Illusion           4
4      Artifact           5
..          ...         ...
60         Crab          61
61    Barbarian          62
62      Centaur          63
63       Spirit          64
64    Equipment          65

[65 rows x 2 columns]

In [12]:
su.columns

Index(['subtype', 'subtype_id'], dtype='object')

In [13]:
su = su[['subtype_id','subtype']]

In [14]:
su

    subtype_id      subtype
0            1  Enchantment
1            2         Aura
2            3     Creature
3            4     Illusion
4            5     Artifact
..         ...          ...
60          61         Crab
61          62    Barbarian
62          63      Centaur
63          64       Spirit
64          65    Equipment

[65 rows x 2 columns]

In [18]:
df.query('rarity == "Uncommon"')

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1,2,Iceberg,NaN,NaN,Enchantment,NaN,NaN,Ice Age,Uncommon,Jeff A. Menges,73,383.0,XUU,Iceberg comes into play with X ice counters on...,NaN,NaN,NaN,NaN,1
4,5,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,Ice Age,Uncommon,Tom Wänerstrand,310,383.0,2,"2, T: Target snow land is no longer snow.\n2, ...",NaN,NaN,NaN,NaN,1
11,12,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,Portal,Uncommon,Adrian Smith,137,NaN,4R,Lava Axe deals 5 damage to your opponent,"Swing your axe as a broom, to sweep away the foe",NaN,NaN,NaN,1
12,13,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,Portal,Uncommon,Christopher Rush,154,NaN,1R,Volcanic Hammer deals 3 damage to any one crea...,"Cast the weight as though it were a die, to se...",NaN,NaN,NaN,1
14,15,Soul Warden,NaN,NaN,Creature,Ceric,NaN,Exodus,Uncommon,Randy Gallegos,21,NaN,W,"Whenever any other creature comes into play, g...",Count carefully the souls and see that none ar...,1,1,NaN,4
16,17,Air Elemental,NaN,NaN,Creature,Elemental,NaN,Portal 2,Uncommon,Doug Chaffee,31,NaN,3UU,Flying,"As insubstantial, and as powerful, as the wind...",4,4,NaN,2
21,22,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,Portal 2,Uncommon,Di'Terlizzi,41,NaN,1UU,Play Mystic Denial only in response to another...,NaN,NaN,NaN,NaN,2
23,24,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,Portal 2,Uncommon,Christopher Rush,32,NaN,2U,"On your turn, before you attack, you may tap A...",NaN,1,1,NaN,2
30,31,Wild Ox,NaN,NaN,Creature,Ox,NaN,Portal 2,Uncommon,Jeffrey R. Busch,150,NaN,3G,Swampwalk (If defending player has any swamps ...,"It has the run of the swamps, and it knows it.",3,3,NaN,2
31,32,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,Portal 2,Uncommon,Ron Spencer,146,NaN,3GG,"If Sylvan Basilisk attacks and is blocked, des...",NaN,2,4,NaN,1
32,33,River Bear,NaN,NaN,Creature,Bear,NaN,Portal 2,Uncommon,Una Fricker,144,NaN,3G,Islandwalk (If defending player has any island...,The bears had been isolated on an island for h...,3,3,NaN,2
40,41,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,Portal 2,Uncommon,Jeffrey R. Busch,20,NaN,1WW,All your creatures get +2/+2 until the end of ...,NaN,NaN,NaN,NaN,1
41,42,Dragon Blood,NaN,Artifact,NaN,NaN,NaN,Urza's Saga,Uncommon,Greg Simanson,293,350.0,3,"3, T: Put a +1/+1 counter on target creature.","Fire in the blood, fire in the belly.",NaN,NaN,NaN,1
42,43,Songstitcher,NaN,NaN,Creature,Cleric,NaN,Urza's Saga,Uncommon,Berry,52,350.0,W,1W: Target attacking creature with flying deal...,The true names of birds are songs woven into t...,1,1,NaN,1
43,44,Waylay,NaN,NaN,Instant,NaN,NaN,Urza's Saga,Uncommon,Greg Staples,56,350.0,2W,Put three Knight tokens into play.\nTreat thes...,"""You reek of corruption,"" spat the knight. ""Wh...",NaN,NaN,NaN,1
44,45,Crazed Skirge,NaN,NaN,Creature,Imp,NaN,Urza's Saga,Uncommon,Ron Spencer,125,350.0,3B,Flying\nCrazed Skirge is unaffected by summoni...,They are Phyrexia's couriers; the messages the...,2,2,NaN,1
52,53,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,Starter 1999,Uncommon,Di'Terlizzi,10,173.0,3W,Put target creature card from your graveyard i...,NaN,NaN,NaN,NaN,1
53,54,Veteran Cavalier,NaN,NaN,Creature,Knight,NaN,Starter 1999,Uncommon,rk post,30,173.0,WW,Attacking doesn't cause Veteran cavalier to tap.,Spirit is the sword and experience the sharpen...,2,2,NaN,1
61,62,Ardent Militia,NaN,NaN,Creature,Soldier,NaN,Sixth Edition,Uncommon,Zina Saunders,3,350.0,4W,Attacking doesn't cause Ardent Militia to tap.,"Some fight for honor and some for gold, but th...",2,5,NaN,1
63,64,Castle,NaN,NaN,Enchantment,NaN,NaN,Sixth Edition,Uncommon,Dameon Willich,6,350.0,3W,Untapped creatures you control get +0/2.,"""Hang out our banners on the outward walls;/Th...",NaN,NaN,NaN,1
79,80,Gravebane Zombie,NaN,NaN,Creature,Zombie,NaN,Sixth Edition,Uncommon,Gary Leach,133,350.0,3B,When Gravebane Zombie would be put into a grav...,NaN,3,2,NaN,1
80,81,Hidden Horror,NaN,NaN,Creature,Horror,NaN,Sixth Edition,Uncommon,Clint Langley,137,350.0,1BB,"When Hidden Horror comes into play, choose and...",NaN,4,4,NaN,1
81,82,Mischievous Poltergeist,NaN,NaN,Creature,Ghost,NaN,Sixth Edition,Uncommon,Di'Terlizzi,144,350.0,2B,Flying\nPay 1 life: Regenerate Mischievous Pol...,"""The past is a ghost that haunts you from the ...",1,1,NaN,1
89,90,Wall of Fire,NaN,NaN,Creature,Wall,NaN,Sixth Edition,Uncommon,Richard Thomas,216,350.0,1RR,(Walls can't attack.)\nR: Wall of Fire gets +1...,"""Struggle, and you will only fan the flames.""\...",0,5,NaN,1
90,91,Creeping Mold,NaN,NaN,Sorcery,NaN,NaN,Sixth Edition,Uncommon,David Seeley,220,350.0,2GG,"Destroy target artifact, land, or enchantment.","""Mold could catch you.""\n—Suq'Ata insult",NaN,NaN,NaN,1
98,99,Mana Prism,NaN,Artifact,NaN,NaN,NaN,Sixth Edition,Uncommon,Margaret Organ-Kean,297,350.0,3,T: Add one colorless mana to your mana pool.\n...,NaN,NaN,NaN,NaN,1
99,100,Obsianus Golem,NaN,Artifact,Creature,Golem,NaN,Sixth Edition,Uncommon,Jesper Myrfors,303,350.0,6,NaN,"""The foot stone is connected to the ankle ston...",4,6,NaN,1
100,101,Rod of Ruin,NaN,Artifact,NaN,NaN,NaN,Sixth Edition,Uncommon,Christopher Rush,309,350.0,4,"3, T: Rod of Ruin deals 1 damage to target cre...",NaN,NaN,NaN,NaN,1
102,103,Chameleon Spirit,NaN,NaN,Creature,Illusion,NaN,Mercadian Masques,Uncommon,Bradley Williams,65,350.0,3U,"As Chameleon Spirit comes into play, choose a ...",NaN,X,X,NaN,1
107,108,Uphill Battle,NaN,NaN,Enchantment,NaN,NaN,Mercadian Masques,Uncommon,Pete Venters,222,350.0,2R,Creatures your opponents play come into play t...,Cho-Manno knew he had no choice but to ally wi...,NaN,NaN,NaN,1
109,110,Fountain of Cho,NaN,NaN,Land,NaN,NaN,Mercadian Masques,Uncommon,Scott Hampton,317,350.0,NaN,Fountain of Cho comes into play tapped.\nT: Pu...,NaN,NaN,NaN,NaN,4
115,116,Reveille Squad,NaN,NaN,Creature,Rebel,NaN,Prophecy,Uncommon,Greg & Tim Hildebrandt,18,143.0,2WW,"Whenever you're attacked, if Reveille Squad is...","""To arms! To arms! The Lion roars!""",3,3,NaN,4
116,117,Sky Weaver,NaN,NaN,Creature,Wizard,NaN,Invasion,Uncommon,Christopher Moeller,74,350.0,1U,2: Target white or black creature gains flying...,"""Let my wisdom give you wings.""",2,1,NaN,1
119,120,Soul Net,NaN,Artifact,NaN,NaN,NaN,Seventh Edition,Uncommon,Ron Spencer,317,350.0,1,Whenever a creature is put into a graveyard fr...,NaN,NaN,NaN,NaN,1
122,123,Slay,NaN,NaN,Instant,NaN,NaN,Planeshift,Uncommon,Ben Thompson,55,143.0,2B,Destroy target green creature. It can't be reg...,"The elves had the edge in guile, skill, and va...",NaN,NaN,NaN,1
126,127,Beloved Chaplain,NaN,NaN,Creature,Cleric,NaN,Odyssey,Uncommon,Darrel Riche,11,350.0,1W,Protection from creatures,"Nomad and Nantuko, eagle and elephant; all the...",1,1,NaN,2
127,128,Mystic Penitent,NaN,NaN,Creature,Nomad,Mystic,Odyssey,Uncommon,Larry Elmore,34,350.0,W,Attacking doesn't cause Mystic Penitent to tap...,NaN,1,1,NaN,2
128,129,Nomad Decoy,NaN,NaN,Creature,Nomad,NaN,Odyssey,Uncommon,Pete Venters,37,350.0,2W,"W, T: Tap target creature.\nThreshold—WW, T: T...","If you can take something from a nomad, it's p...",1,2,NaN,2
135,136,Deep Reconnaissance,NaN,NaN,Sorcery,NaN,NaN,Odyssey,Uncommon,Jeff Remmer,236,350.0,2G,Search your library for a basic land card and ...,NaN,NaN,NaN,NaN,2
136,137,Nantuko Elder,NaN,NaN,Creature,Insect,Druid,Odyssey,Uncommon,Daren Bader,254,350.0,2G,T: Add 1G to your mana pool,"Plant a field with wishes, and you will grow m...",1,2,NaN,2
137,138,Roar of the Wurm,NaN,NaN,Sorcery,NaN,NaN,Odyssey,Uncommon,Kev Walker,266,350.0,6G,Put a 6/6 green Wurm creature token into play....,NaN,NaN,NaN,NaN,2
146,147,Battle Screech,NaN,NaN,Sorcery,NaN,NaN,Judgement,Uncommon,Randy Gallegos,3,143.0,2WW,Put two 1/1 white Bird creature tokens with fl...,NaN,NaN,NaN,NaN,2
147,148,Spurmage Advocate,NaN,NaN,Creature,Nomad,NaN,Judgement,Uncommon,Ron Spears,27,143.0,W,T: Return two target cards in an opponent's gr...,"""Our unity humbles our foes.""",1,1,NaN,2
148,149,Unquestioned Authority,NaN,NaN,Enchantment,NaN,NaN,Judgement,Uncommon,Alex Horley,31,143.0,2W,"When Unquestioned Authority comes into play, d...","""Only the Ancestor should be revered.""\n—Mysti...",NaN,NaN,NaN,2
149,150,Valor,NaN,NaN,Creature,Incarnation,NaN,Judgement,Uncommon,Kev Walker,32,143.0,3W,First strike\nAs long as Valor is in your grav...,"""The cracks widened, the shell crumbled, and V...",2,2,NaN,1
150,151,Wormfang Turtle,NaN,NaN,Creature,Nightmare,Beast,Judgement,Uncommon,John Avon,60,143.0,2U,"When Wormfang Turtle comes into play, remove a...",Chainer's admirers keep his dreams alive.,2,4,NaN,1
151,152,Wormfang Crab,NaN,NaN,Creature,Nightmare,Crab,Judgement,Uncommon,Glen Angus,56,143.0,3U,Wormfang Crab is unblockable.\nWhen Wormfang C...,NaN,3,6,NaN,1
152,153,Tunneler Wurm,NaN,NaN,Creature,Wurm,NaN,Judgement,Uncommon,Jeff Easley,135,143.0,6GG,Discard a card from your hand: Regenerate Tunn...,"If an anurid's lucky, it'll find a warm tunnel...",6,6,NaN,2
153,154,Exoskeletal Armor,NaN,NaN,Enchantment,NaN,NaN,Judgement,Uncommon,Wayne England,114,143.0,1G,"Enchanted creature gets +X/+X, where X is the ...","""We use only what we need—but in times of stri...",NaN,NaN,NaN,3
154,155,Brawn,NaN,NaN,Creature,Incarnation,NaN,Judgement,Uncommon,Matt Cavota,107,143.0,3G,Trample\nAs long as Brawn is in your graveyard...,"""'I have arrived,' bellowed Brawn, and the pla...",3,3,NaN,2
155,156,Anurid Swarmsnapper,NaN,NaN,Creature,Beast,NaN,Judgement,Uncommon,John Matson,105,143.0,2G,Anurid Swarmsnapper may block as though it had...,Anurids have the problem of airborne invaders ...,1,4,NaN,2
176,177,Willbender,NaN,NaN,Creature,Wizard,NaN,Legions,Uncommon,Eric Peterson,58,145.0,1U,Morph 1U (You may play this face down as a 2/2...,NaN,1,2,NaN,2
177,178,Branchsnap Lorian,NaN,NaN,Creature,Beast,NaN,Legions,Uncommon,Heather Hudson,118,145.0,1GG,Trample\nMorph G (You may play this face down ...,NaN,4,1,NaN,1
178,179,Pemmin's Aura,NaN,NaN,Enchantment,NaN,NaN,Scourge,Uncommon,Greg Staples,45,143.0,1UU,U: Untap enchanted creature\nU: Enchanted crea...,NaN,NaN,NaN,NaN,4
179,180,Flayed Nim,NaN,NaN,Creature,Skeleton,NaN,Mirrodin,Uncommon,Trevor Hairsine,65,306.0,3B,Whenever Flayed Nim deals combat damage to a c...,NaN,2,2,NaN,1

In [19]:
df.dtypes

permanent_id               int64
card_name                 object
supertype                 object
subtype_a                 object
subtype_b                 object
subtype_c                 object
subtype_d                 object
expansion_symbol          object
rarity                    object
artist_information        object
collectors_number         object
expansion_total_cards    float64
mana_cost                 object
text_box                  object
flavor_text               object
punch                     object
toughness                 object
starting_loyalty         float64
quantity                   int64
dtype: object