In [32]:
import pandas as pd
import glob

# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer Woo/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_04_08/*.csv")

# 2. Use list comprehension to read all files and concat them
df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060 entries, 0 to 1059
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           974 non-null    float64
 1   card_name              1059 non-null   object
 2   supertype              8 non-null      object
 3   subtype_a              40 non-null     object
 4   subtype_b              1037 non-null   object
 5   subtype_c              742 non-null    object
 6   subtype_d              390 non-null    object
 7   subtype_e              28 non-null     object
 8   expansion_symbol       1059 non-null   object
 9   rarity                 1059 non-null   object
 10  artist_information     1057 non-null   object
 11  collectors_number      1059 non-null   object
 12  expansion_total_cards  1024 non-null   float64
 13  mana_cost              1030 non-null   object
 14  text_box               1033 non-null   object
 15  flavor_text            695 non-null    object
 16  punch                  641 non-null    object
 17  toughness              641 non-null    object
 18  starting_loyalty       0 non-null      float64
 19  quantity               1056 non-null   object
dtypes: float64(3), object(17)
memory usage: 165.8+ KB

In [34]:
df

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,Richard Kane Ferguson,69,383.0,U,Enchant Creature\nEnchanted creature gets +2+0...,Never underestimate the poweor of the soul unl...,NaN,NaN,NaN,1
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,Jeff A. Menges,73,383.0,XUU,Iceberg comes into play with X ice counters on...,NaN,NaN,NaN,NaN,1
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,Quinton Hoover,84,383.0,UU,B: Counter target spell that targets mistfolk.,"""Although my official log will state there is ...",1,2,NaN,1
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,"Ken Meyer, Jr.",100,383.0,1U,Enchant creature\nEnchanted creature has flyin...,"""Give me wings to fly and speed to strike. In ...",NaN,NaN,NaN,1
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,Tom Wänerstrand,310,383.0,2,"2, T: Target snow land is no longer snow.\n2, ...",NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,NaN,Safewright Quest,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Dan Scott,240,301.0,{G/W},Search your library for a Forest or Plains car...,Elves search for sources of beauty in a nighte...,NaN,NaN,NaN,6
1056,NaN,Shield of the Oversoul,NaN,NaN,Enchantment,Aura,NaN,NaN,Shadowmoor,Common,Steven Belledin,242,301.0,2{G/W},Enchant creature\nAs long as enchanted creatur...,NaN,NaN,NaN,NaN,6
1057,NaN,Toil to Renown,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Larry MacDougall,130,301.0,1G,"You gain 1 life for each tapped artifact, crea...","The last survivor of her patrol, the warrior r...",NaN,NaN,NaN,8
1058,NaN,Viridescent Wisps,NaN,NaN,Instant,NaN,NaN,NaN,Shadowmoor,Common,Jim Nelson,132,301.0,G,Target creature becomes green and gets +1/+0 u...,"In the wisps that night, the once timid boggar...",NaN,NaN,NaN,6
1059,NaN,Wildslayer Elves,NaN,NaN,Creature,Elf,Warrior,NaN,Shadowmoor,Common,Dave Kendall,133,301.0,3G,Wither (This deals damage to creatures in teh ...,Some elves battled too long in the deep shadow...,3.0,3.0,NaN,4

In [27]:
df['permanent_id'] = range(1, len(df) +1)

In [29]:
df.tail()

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1055,1056,Safewright Quest,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Dan Scott,240,301.0,{G/W},Search your library for a Forest or Plains car...,Elves search for sources of beauty in a nighte...,NaN,NaN,NaN,6
1056,1057,Shield of the Oversoul,NaN,NaN,Enchantment,Aura,NaN,NaN,Shadowmoor,Common,Steven Belledin,242,301.0,2{G/W},Enchant creature\nAs long as enchanted creatur...,NaN,NaN,NaN,NaN,6
1057,1058,Toil to Renown,NaN,NaN,Sorcery,NaN,NaN,NaN,Shadowmoor,Common,Larry MacDougall,130,301.0,1G,"You gain 1 life for each tapped artifact, crea...","The last survivor of her patrol, the warrior r...",NaN,NaN,NaN,8
1058,1059,Viridescent Wisps,NaN,NaN,Instant,NaN,NaN,NaN,Shadowmoor,Common,Jim Nelson,132,301.0,G,Target creature becomes green and gets +1/+0 u...,"In the wisps that night, the once timid boggar...",NaN,NaN,NaN,6
1059,1060,Wildslayer Elves,NaN,NaN,Creature,Elf,Warrior,NaN,Shadowmoor,Common,Dave Kendall,133,301.0,3G,Wither (This deals damage to creatures in teh ...,Some elves battled too long in the deep shadow...,3.0,3.0,NaN,4

In [40]:
row_subtypes = df.iloc[1059, 3:8].to_numpy()

In [41]:
row_subtypes

array([nan, 'Creature', 'Elf', 'Warrior', nan], dtype=object)

In [ ]:
import math
import numpy as np

for i, row in enumerate(df):
    subtypes = df.iloc[i, 3:8].to_numpy()
        for type in subtypes:
            if math.isnan(type):
                continue
            else:
                cursor.execute("SELECT subtype_id FROM subtype WHERE subtype = %s", (type))
                subtype_id = cursor.fetchone()[0]
                cursor.execute("INSERT INTO permanent_junction_subtype (permnent_id, subtype_id) VALUES (%s, %s)" (i, subtype_id))
                connection.commit()
    subtypes.clear()